In [1]:
import numpy as np

In [2]:
num = [1,2,3,4,5]

In [3]:
num = np.array(num)

In [4]:
num

array([1, 2, 3, 4, 5])

In [5]:
#now lets chekc for 2d array
num1 = [[1,2,3,4],[5,6,8,7]]

In [6]:
num1 = np.array(num1)

In [7]:
num1

array([[1, 2, 3, 4],
       [5, 6, 8, 7]])

In [8]:
num1.ndim #show the dimension of the array

2

In [9]:
num1.shape #show number of columns and rows or shape of array

(2, 4)

In [10]:
#some functions for numpy like zeros,ones,eye,diag,rand,randint,randn
matr = np.zeros(5)

In [11]:
matr

array([0., 0., 0., 0., 0.])

In [15]:
matr1 = np.zeros((2,4))

In [19]:
matr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
matr2 = np.ones(4)

In [22]:
matr2

array([1., 1., 1., 1.])

In [28]:
matr2 = np.ones((5,6))

In [29]:
matr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
arrEye = np.eye(4)

In [32]:
arrEye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
arrEye = np.eye((5))

In [35]:
arrEye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
arrEye = np.eye(3,4)

In [37]:
arrEye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [49]:
newArr = np.diag([1,75,6,0])

In [50]:
newArr

array([[ 1,  0,  0,  0],
       [ 0, 75,  0,  0],
       [ 0,  0,  6,  0],
       [ 0,  0,  0,  0]])

In [52]:
randEx = np.random.rand(5) #it will give values between 0 to 1

In [53]:
randEx

array([0.63897285, 0.02497556, 0.15283865, 0.72197285, 0.87946342])

In [62]:
# it wiil genrate a 2d array with random numbers
randEx = np.random.rand(2,3)

In [63]:
randEx

array([[0.99419094, 0.00519409, 0.15716454],
       [0.09706667, 0.80177904, 0.38245647]])

In [59]:
#randint example below -- suppose we need 4 numbers between 1 (inclusive) to 15 (exculsive)
randEx1 = np.random.randint(1,15,4)

In [60]:
randEx1

array([ 4, 14,  9, 10])

In [64]:
#randn will genrate numbers with respect to zero as a centre
randEx2 = np.random.randn(5)

In [65]:
randEx2

array([-1.30268401, -0.04035453,  0.01173041,  0.2855387 , -1.22268587])

In [66]:
#randn for 2d array
randEx3 = np.random.randn(4,5)

In [67]:
randEx3

array([[-2.00513228,  0.37571361,  0.65333858,  2.32608955, -1.06126469],
       [-1.54800937, -0.80711691,  0.13686854, -1.00656221,  0.32558954],
       [ 0.06369736, -0.35081238, -0.5463562 ,  0.16476528, -0.03604361],
       [-0.63662786,  0.13945843, -0.9085167 , -0.2937773 , -0.73689831]])