In [1]:
import numpy as np

In [2]:
np.random.seed(123)
matrix1 = np.random.randint(1,15,9).reshape(3,3)
matrix2 = np.random.randint(1,10,9).reshape(3,3)

In [3]:
matrix1

array([[14,  3, 13],
       [ 3,  7,  2],
       [ 4, 11, 12]])

In [4]:
matrix2

array([[7, 2, 1],
       [2, 1, 1],
       [4, 5, 1]])

In [6]:
#concatination of two matrix horizontal pass tuple()
np.hstack((matrix1,matrix2))

array([[14,  3, 13,  7,  2,  1],
       [ 3,  7,  2,  2,  1,  1],
       [ 4, 11, 12,  4,  5,  1]])

In [7]:
np.vstack((matrix1,matrix2))

array([[14,  3, 13],
       [ 3,  7,  2],
       [ 4, 11, 12],
       [ 7,  2,  1],
       [ 2,  1,  1],
       [ 4,  5,  1]])

In [8]:
#lets try this on 1d array
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [9]:
arr1

array([1, 2, 3, 4])

In [10]:
arr2

array([5, 6, 7, 8])

In [11]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])