In [15]:
import numpy as np

In [16]:
matrix = np.array([[12,34,54],[6,5,42],[9,62,7]])
matrix

array([[12, 34, 54],
       [ 6,  5, 42],
       [ 9, 62,  7]])

In [17]:
#indexing using double bracket notation
matrix[0][1]

34

In [18]:
matrix[2][1]

62

In [19]:
#indexing using single bracket notation (Recommended)
matrix

array([[12, 34, 54],
       [ 6,  5, 42],
       [ 9, 62,  7]])

In [20]:
matrix[0,1]

34

In [21]:
matrix[2,2]

7

In [22]:
#Slicing using single bracket notation
matrix

array([[12, 34, 54],
       [ 6,  5, 42],
       [ 9, 62,  7]])

In [23]:
matrix[:1] 

array([[12, 34, 54]])

In [24]:
matrix[:2]

array([[12, 34, 54],
       [ 6,  5, 42]])

In [31]:
matrix[:2,:2]

array([[12, 34],
       [ 6,  5]])

In [34]:
matrix[1:,1:]

array([[ 5, 42],
       [62,  7]])

In [36]:
np.random.seed(123)
arr1 = np.random.randint(1,101,25).reshape(5,5)
arr1

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [37]:
# 87,988,97
#33,47,97
#79,37,97
arr1[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])