In [1]:
import numpy as np

In [2]:
arr = np.array([4,5,67,7,12,56])

In [3]:
arr

array([ 4,  5, 67,  7, 12, 56])

In [4]:
sciled_arr = arr[:2]

In [5]:
sciled_arr

array([4, 5])

In [6]:
sciled_arr[:2] = 0

In [7]:
sciled_arr

array([0, 0])

In [8]:
arr

array([ 0,  0, 67,  7, 12, 56])

In [9]:
#now see both arrays are changed (it is called view a.k.a refrence) - solution for this is copy
#now lets take an example
arr1 = np.array([6,4,5,8,23,98])
arr1

array([ 6,  4,  5,  8, 23, 98])

In [11]:
sliced_arr1 = arr1[:2].copy()
sliced_arr1

array([6, 4])

In [12]:
sliced_arr1

array([6, 4])

In [13]:
arr1

array([ 6,  4,  5,  8, 23, 98])