In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr1 = arr>5
arr1

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
arr[arr1]

array([ 6,  7,  8,  9, 10])

In [5]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [6]:
arr[arr==5]

array([5])