In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr * 2

array([2, 4, 6, 8])

In [4]:
arr%2

array([1, 0, 1, 0], dtype=int32)

In [5]:
arr ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [6]:
# you can also do this wih 2d array
arr1 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [11]:
arr1/0

<ipython-input-11-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [13]:
arr1 /4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])